version: "3"

services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust/
    command: -f /mnt/locust/tests/socket_user.py,/mnt/locust/tests/test_ramp_up_hold.py --master --expect-workers 2
    # -f /mnt/locust/tests/socket_user.py,/mnt/locust/tests/test_ramp_up_hold.py --master --expect-workers 2 --headless --only-summary --html /mnt/locust/reports/report.html

  worker1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust/
    command: -f /mnt/locust/tests/socket_user.py,/mnt/locust/tests/test_ramp_up_hold.py --worker --master-host master

  worker2:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust/
    command: -f /mnt/locust/tests/socket_user.py,/mnt/locust/tests/test_ramp_up_hold.py --worker --master-host master
